Extract Bedrock-specific components from 'veres-one-context'
digitalbazaar/bedrock-veres-one-context pull request #2
Opened 2018-09-27 20:49 UTC by dmitrizagidulin

Addresses https://github.com/veres-one/veres-one-context/issues/2.

(Depends on PR https://github.com/veres-one/veres-one-context/pull/3 merged and published to `v3.0.0`.)

2018-09-27 21:02 UTC, mattcollier commented
@dmitrizagidulin please copy license and .gitgnore from this location: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity-es-most-recent-participants/tree/implementation

2018-09-27 21:14 UTC, dmitrizagidulin commented
@mattcollier Done, thanks!

2018-10-01 15:02 UTC, mattcollier requested changes

2018-10-01 15:02 UTC, mattcollier commented on package.json
> +  "version": "2.0.1-0",
This needs to be set to "0.0.1-0" in preparation for a 1.0.0 release.

2018-10-01 15:45 UTC, merged